// react-app/src/Content.tsx
import React from "react";
import PropTypes from 'prop-types';

import "./index.css";

export default function Content({name}) {
  return (
    <div className="react-container">
      <div>Name: {name ?? "React"}</div>
      <div>Framework: react</div>
      <div>Language: TypeScript</div>
      <div>(:3001)</div>
      <lit-button />
    </div>
  );
}

Content.propTypes = {
  name: PropTypes.string
}

// vue-app/src/Content.vue
<template>
  <div class="vue-container">
    <div>Name: vue-app</div>
    <div>Framework: vue3</div>
    <div>Language: TypeScript</div>
    <div>(:3002)</div>
    <lit-button></lit-button>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'
  import "./index.css";

  export default defineComponent({});
</script>
